
USE XXXXXXXXXXXXX; -- DATABASE NAME
-- CLEAN THE DATA IN CASE OF PREVIUS DATA
DROP TABLE IF EXISTS Messages;
DROP TABLE IF EXISTS Users_Messages;
DROP TABLE IF EXISTS Users_Contacts;
DROP TABLE IF EXISTS Users;
-- TABLES CREATION
create table Users(
UserId INT PRIMARY KEY AUTO_INCREMENT,
Username VARCHAR(50) NOT NULL UNIQUE,
Password VARCHAR(20) NOT NULL
);
create table Users_Contacts(
UserId INT NOT NULL,
ContactId INT NOT NULL,
Blocked BOOLEAN NOT NULL,
PRIMARY KEY (ContactId,UserId),
FOREIGN KEY(ContactId) REFERENCES Users(UserId)
);
create table Users_Messages(
ChatId INT NOT NULL,
UserId INT NOT NULL,
PRIMARY KEY(ChatId,UserId),
FOREIGN KEY(UserId) REFERENCES Users(UserId)
);
create table Messages(
MessageId INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
UserId INT NOT NULL,
ChatId INT NOT NULL,
Text VARCHAR(5000) NOT NULL,
Date TIMESTAMP NOT NULL,
Readed BOOLEAN NOT NULL,
CONSTRAINT FOREIGN KEY(ChatId) REFERENCES Users_Messages(ChatId),
CONSTRAINT FOREIGN KEY(UserId) REFERENCES Users(UserId)
)
